import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "sonner";

import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import MenuOptions from "@/components/navabar/MenuOptions";
import Navbar from "@/components/navabar/Navbar";
import { NextRequest } from "next/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = cookies().get("token");
  const userToken = cookies().get("token");
  console.log("token", token, "user", userToken);
  return (
    <html lang="en">
      <body className={`${inter.className} flex h-screen overflow-hidden`}>
        <aside className="  shrink-0">{userToken && <MenuOptions />}</aside>
        <main className="flex flex-col flex-grow overflow-hidden">
          <header className="w-full">{userToken && <Navbar />}</header>
          <div className="flex-grow overflow-auto">{children}</div>
        </main>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
